import streamlit as st
import pandas as pd
import joblib

# Load the trained Machine Learning model and expected columns
model = joblib.load('civic_model.pkl')
model_columns = joblib.load('model_columns.pkl')

# Configure the web page settings
st.set_page_config(page_title="Civic Tech Predictor", layout="centered")

# Main Header and Description
st.title("Civic Tech Grievance & Delay Analyzer")
st.write("An interactive tool to predict the estimated resolution time for public infrastructure complaints based on historical data patterns.")
st.markdown("---")

# User Input Form
st.header("Enter Complaint Details")

col1, col2 = st.columns(2)

with col1:
    category = st.selectbox("Select Issue Category", ['Road Construction', 'Sewerage', 'Street Light', 'Water Supply', 'Garbage Collection'])
    priority = st.selectbox("Select Priority Level", ['High', 'Medium', 'Low'])

with col2:
    area = st.selectbox("Select Geographic Area", ['Indra Nagar', 'Civil Lines', 'Basharatpur', 'Mohaddipur', 'Golghar'])

# Prediction Logic
if st.button("Predict Resolution Delay", type="primary"):
    
    # 1. Capture user inputs into a DataFrame
    input_data = pd.DataFrame([[category, area, priority]], columns=['Category', 'Area', 'Priority'])
    
    # 2. Apply One-Hot Encoding just like the training phase
    input_encoded = pd.get_dummies(input_data)
    
    # 3. Align input columns with model training columns (fill missing with 0)
    input_encoded = input_encoded.reindex(columns=model_columns, fill_value=0)
    
    # 4. Generate prediction
    prediction = model.predict(input_encoded)[0]
    
    # 5. Display the result
    st.success(f"**Estimated Resolution Time:** {prediction:.1f} days")
    st.info("Note: This prediction is generated by a Random Forest algorithm and is subject to natural variance based on real-world operational delays.")